# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: retrieval.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'retrieval.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fretrieval.proto\x12\tretrieval\"-\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\":\n\x0eSearchResponse\x12(\n\x06\x63hunks\x18\x01 \x03(\x0b\x32\x18.retrieval.DocumentChunk\"?\n\rDocumentChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\x32]\n\x11\x44ocumentRetriever\x12H\n\x0fSearchDocuments\x12\x18.retrieval.SearchRequest\x1a\x19.retrieval.SearchResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'retrieval_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST']._serialized_start=30
  _globals['_SEARCHREQUEST']._serialized_end=75
  _globals['_SEARCHRESPONSE']._serialized_start=77
  _globals['_SEARCHRESPONSE']._serialized_end=135
  _globals['_DOCUMENTCHUNK']._serialized_start=137
  _globals['_DOCUMENTCHUNK']._serialized_end=200
  _globals['_DOCUMENTRETRIEVER']._serialized_start=202
  _globals['_DOCUMENTRETRIEVER']._serialized_end=295
# @@protoc_insertion_point(module_scope)
