# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import retrieval_pb2 as retrieval__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in retrieval_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentRetrieverStub(object):
    """定义检索服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchDocuments = channel.unary_unary(
                '/retrieval.DocumentRetriever/SearchDocuments',
                request_serializer=retrieval__pb2.SearchRequest.SerializeToString,
                response_deserializer=retrieval__pb2.SearchResponse.FromString,
                _registered_method=True)


class DocumentRetrieverServicer(object):
    """定义检索服务
    """

    def SearchDocuments(self, request, context):
        """混合检索核心接口：接收问题，返回最相关的文档片段
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentRetrieverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchDocuments,
                    request_deserializer=retrieval__pb2.SearchRequest.FromString,
                    response_serializer=retrieval__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'retrieval.DocumentRetriever', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('retrieval.DocumentRetriever', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentRetriever(object):
    """定义检索服务
    """

    @staticmethod
    def SearchDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retrieval.DocumentRetriever/SearchDocuments',
            retrieval__pb2.SearchRequest.SerializeToString,
            retrieval__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
